import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateCrewEnums1777702934232 implements MigrationInterface {
    name = 'UpdateCrewEnums1777702934232'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."crew_members_email_key"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "rank"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "middleName"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "birthDate"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "photo"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "licenseType"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "licenseExpiry"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "medicalCert"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "medicalExpiry"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "medicalClass"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "education"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "graduationYear"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "acTypePrimary"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "acTypeSecondary"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "acClass"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "totalFlightHours"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "totalHoursPrimary"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "totalHoursYear"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "totalPicHours"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "totalSicHours"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "totalNightHours"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "totalIfrHours"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "totalLandings"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "checkRideDate"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "simCheckDate"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "lineCheckDate"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "profCheckDate"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "allowNight"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "allowImc"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "allowSmu"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "allowUmp"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "allowMountain"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "allowSeaplane"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "allowCargo"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "allowDangerous"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "allowInstructor"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "allowExaminer"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "hireDate"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "remarks"`);
        await queryRunner.query(`CREATE TYPE "public"."crew_members_status_enum" AS ENUM('active', 'inactive', 'on_leave', 'suspended')`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "status" "public"."crew_members_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "totalHours" numeric(8,1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP CONSTRAINT "crew_members_pkey"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD CONSTRAINT "PK_722c7a3d215feeada44379f7099" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "firstName" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "lastName" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD CONSTRAINT "UQ_0a3ab2be4a095b899f64752670e" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "licenseNumber"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "licenseNumber" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "category"`);
        await queryRunner.query(`CREATE TYPE "public"."crew_members_category_enum" AS ENUM('PILOT', 'INSTRUCTOR', 'ENGINEER', 'TECHNICIAN', 'MECHANIC')`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "category" "public"."crew_members_category_enum" NOT NULL DEFAULT 'PILOT'`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "position"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "position" character varying`);
        await queryRunner.query(`ALTER TABLE "crew_members" ALTER COLUMN "createdAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "crew_members" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "crew_members" ALTER COLUMN "updatedAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "crew_members" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "crew_members" ALTER COLUMN "updatedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "crew_members" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "crew_members" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "crew_members" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "position"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "position" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "phone" text`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "category"`);
        await queryRunner.query(`DROP TYPE "public"."crew_members_category_enum"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "category" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "licenseNumber"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "licenseNumber" text`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP CONSTRAINT "UQ_0a3ab2be4a095b899f64752670e"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "email" text`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "lastName" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "firstName" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP CONSTRAINT "PK_722c7a3d215feeada44379f7099"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD CONSTRAINT "crew_members_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "totalHours"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."crew_members_status_enum"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "remarks" text`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "hireDate" TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "allowExaminer" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "allowInstructor" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "allowDangerous" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "allowCargo" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "allowSeaplane" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "allowMountain" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "allowUmp" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "allowSmu" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "allowImc" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "allowNight" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "profCheckDate" TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "lineCheckDate" TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "simCheckDate" TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "checkRideDate" TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "totalLandings" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "totalIfrHours" double precision NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "totalNightHours" double precision NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "totalSicHours" double precision NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "totalPicHours" double precision NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "totalHoursYear" double precision NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "totalHoursPrimary" double precision NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "totalFlightHours" double precision NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "acClass" text`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "acTypeSecondary" text`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "acTypePrimary" text`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "graduationYear" integer`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "education" text`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "medicalClass" integer`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "medicalExpiry" TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "medicalCert" text`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "licenseExpiry" TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "licenseType" text`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "photo" text`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "address" text`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "birthDate" TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "middleName" text`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "rank" text NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "crew_members_email_key" ON "crew_members" ("email") `);
    }

}
